# These are supported funding model platforms

github: https://github.com/SemihK
patreon: patreon.com/semihkesgin


# repo:     https://github.com/SemihK/AvGPT
# filename: FUNDING.YML

github: Semihk

