# These are supported funding model platforms

github: https://github.com/SemihK
patreon: semihkesgin
custom: ["https://www.buymeacoffee.com/semihkesgin", https://www.buymeacoffee.com/]


# repo:     https://github.com/SemihK/AvGPT
# filename: FUNDING.YML

github: Semihk

